### ISSUE TITLE
[Release Testing]1-26 : 선택된 공지/이벤트 정보가 수정화면에 표시되고, 이를 변경 후 저장하면 그 내용이 즉시 반영

### ISSUE THREAD

**Issue by yjidh98** [SW-PROJECT-2021/sw_front#23]
Expected behavior
 : 수정 화면에 선택된 공지/이벤트의 정보(이름, 상세, 기간, 이미지)가 표시되고 이를 변경 후 저장하면 즉시 저장됨.

Actual behavior
 : 수정 화면에 선택된 공지/이벤트의 기간, 이미지가 표시되지 않음

**Comment by InHyeok-J** [comment]
수정완료
