### ISSUE TITLE
[Release Testing] 2-12 : 이름, 가격 또는 최신 등록 상품 순으로 정렬

### ISSUE THREAD

**Issue by yjidh98** [SW-PROJECT-2021/sw_front#24]
Expected behavior
 : 사용자가 이름, 가격, 등록 날짜 중 선택하여 이름, 가격, 최신 등록 순으로 상품을 정렬할 수 있어야한다.

Actual behavior
: 가격, 등록 날짜 순으로 정렬이 가능하지만, 이름 순으로 정렬을 할 수 없다.

**Comment by Seongil-Shin** [comment]
이름순 정렬 추가하였습니다.

**Comment by yjidh98** [comment]
구현 목록에 이름, 가격, "또는" 최신등록순으로 라고 되어있어서 엑셀 파일에는 오류 체크 안하고 제출합니당!! 이 이슈로는 감점요인 없으실거에요..!
