### ISSUE TITLE
[Release Testing] 1-19 : ID, PW, 이름, 이메일 주소는 필수 정보

### ISSUE THREAD

**Issue by yjidh98** [SW-PROJECT-2021/sw_front#26]
Expected behavior
: 유효한 id, pw, 이름, 이메일 주소를 입력할 경우 회원가입 가능

Actual behavior
 : 이름 값으로 " " 또는" ," 만 입력해도 회원가입이 가능하다

**Comment by InHyeok-J** [comment]
1-9 , 1-10 말씀하시는건가요 ?
유효한 id, pw, 이름, 이메일 주소를 입력할 경우 회원가입 가능이라는 요구사항이 있는지 궁금합니다  공백 값 제출 하려고하면 1-10에서 공백검사는 하고 있습니다

**Comment by yjidh98** [comment]
넵 1-10 로 제목 수정했습니다!
 이름은 필수정보이므로 " " (띄어쓰기), "," 등은 잘못된 입력임을 안내하는 기능이 요구된다고 판단하였습니다

**Comment by InHyeok-J** [comment]
수정완료
